shinyUI(fluidPage(
  titlePanel("AUC Calculator"),
  titlePanel(h6(paste0("This is a calculator that takes the output (the number of positive examples (integer, positive), negative ",
        "examples (integer, positive), and the risk score (positive) of each leaf) of a three-level decision tree (up to 8 leaves), displays ",
        "the associated ROC curve, and calculates the AUC."))),
  fluidRow(
    column(6,"Leaf Values",
           fluidRow(column(2,"# Pos", 
                           numericInput('pos1', label=NULL, 0, min = 0, max = NA, step = 1),
                           numericInput('pos2', label=NULL, 3, min = 0, max = NA, step = 1),
                           numericInput('pos3', label=NULL, 12, min = 0, max = NA, step = 1),
                           numericInput('pos4', label=NULL, 8, min = 0, max = NA, step = 1),
                           numericInput('pos5', label=NULL, 5, min = 0, max = NA, step = 1),
                           numericInput('pos6', label=NULL, 7, min = 0, max = NA, step = 1),
                           numericInput('pos7', label=NULL, 5, min = 0, max = NA, step = 1),
                           numericInput('pos8', label=NULL, 1, min = 0, max = NA, step = 1)),
                    column(2,"# Neg", 
                           numericInput('neg1', label=NULL, 0, min = 0, max = NA, step = 1),
                           numericInput('neg2', label=NULL, 6, min = 0, max = NA, step = 1),
                           numericInput('neg3', label=NULL, 2, min = 0, max = NA, step = 1),
                           numericInput('neg4', label=NULL, 8, min = 0, max = NA, step = 1),
                           numericInput('neg5', label=NULL, 3, min = 0, max = NA, step = 1),
                           numericInput('neg6', label=NULL, 9, min = 0, max = NA, step = 1),
                           numericInput('neg7', label=NULL, 15, min = 0, max = NA, step = 1),
                           numericInput('neg8', label=NULL, 7, min = 0, max = NA, step = 1)),
                    column(2,"Risk",
                           numericInput('risk1', label=NULL, .1, min = 0, max = NA, step = .01),
                           numericInput('risk2', label=NULL, .2, min = 0, max = NA, step = .01),
                           numericInput('risk3', label=NULL, .8, min = 0, max = NA, step = .01),
                           numericInput('risk4', label=NULL, .3, min = 0, max = NA, step = .01),
                           numericInput('risk5', label=NULL, .55, min = 0, max = NA, step = .01),
                           numericInput('risk6', label=NULL, .5, min = 0, max = NA, step = .01),
                           numericInput('risk7', label=NULL, .2, min = 0, max = NA, step = .01),
                           numericInput('risk8', label=NULL, 0, min = 0, max = NA, step = .01)))),
    column(6,h3("Results"), h4(textOutput("AUC")),
           plotOutput("ROC"))
  )
))